### ISSUE TITLE
Can I pass an asynchronous function to retry?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [ihrwein/backoff#10]
The definition of trait `Operation<T, E>` is:
```rust
fn call_op(&mut self) -> Result<T, Error<E>>;
```
so, the compiler cannot regard an asynchronous function as being `Operation`, since all asynchronous functions returns `Future<...>`, thus one cannot call a `retry` function to it.

Is there a way to perform retrying on an asynchronous function?

**Comment by TonalidadeHidrica** [comment]
I'm new to Rust so it may be that I'm just missing an important point on this language.

**Comment by andrewbanchich** [comment]
I am wondering this as well @ihrwein . Any thoughts on supporting async functions?

**Comment by dvush** [comment]
I already wrote simple implementation based on `backoff-futures`  crate (which is itself a wrapper around this crate) 
https://github.com/jakubadamw/backoff-futures/pull/1

@ihrwein what do you think about merging it here?
