### ISSUE TITLE
New version release with the `rand:0.7` dependency

### ISSUE THREAD

**Issue by jakubadamw** [ihrwein/backoff#11]
Hey there!

Thanks very much for authoring this crate. Would you be willing to release a new version with the version bump for `rand` (0.7) that's in master now? The backoff's dependency on `rand:0.6` is artificially increasing the number of dependencies of my crates when some of their other dependencies use `rand:0.7`.

Thanks!

**Comment by ihrwein** [comment]
Hello! I've released a `0.2.0` with async support which includes rand `0.7.0`. Please let me know how it goes, I might issue a patch release on the 0.1.x line if needed.

**Comment by jakubadamw** [comment]
@ihrwein, that's great, thank you! I myself don't need a `0.1.x` patch, so I'm happy to see this issue closed. :)
