### ISSUE TITLE
Consider implementing Clone for backoff::ExponentialBackoff

### ISSUE THREAD

**Issue by gliderkite** [ihrwein/backoff#19]
If feasible and in line with the desired semantic, it would be useful to implement `Clone` for `backoff::ExponentialBackoff`.

**Comment by saskenuba** [comment]
Indeed `ExponentialBackoff` should be cloneable, all fields are duration/instants, which all implement `Copy`.

**Comment by coyotebush** [comment]
`backoff::exponential::ExponentialBackoff` now implements `Clone`, but `backoff::ExponentialBackoff` (the type alias) does not. Looks like `backoff::SystemClock` needs a `Clone` impl, which should be trivial/derivable.
