### ISSUE TITLE
Update to tokio 0.3

### ISSUE THREAD

**Issue by UkonnRa** [ihrwein/backoff#21]
Because tokio releases version 0.3 https://crates.io/crates/tokio, please update the dependencies, thanks

**Comment by dead10ck** [comment]
There's a 1.0 now

**Comment by akashgurava** [comment]
looks like work started 👍

**Comment by ihrwein** [comment]
Yes, tokio 1.0 update was done in https://github.com/ihrwein/backoff/pull/23. The feature flags were changes which is a breaking change, so I thought I'll bundle in more changes into a 0.3.0 release: https://github.com/ihrwein/backoff/issues/27

Can we close this issue?

**Comment by ihrwein** [comment]
Closing it as master branch was updated and we'll issue a release soon.
