### ISSUE TITLE
0.3.0 Release

### ISSUE THREAD

**Issue by ihrwein** [ihrwein/backoff#27]
Checklist for 0.3.0:
* [x] tokio 1.0 support https://github.com/ihrwein/backoff/pull/23
* [x] Operation/FutureOperation -> FnMut, Future simplification
* [x] Listing all breaking changes in README with migration instructions
* [x] All dependencies are up to date
* [x] Any planned breaking changes in API resolved
* [x] Simplified README

Postponed for a later release:
* [ ] `no_std` support

**Comment by coolreader18** [comment]
Is 0.3 ready to be released now? It seems like breaking changes have been made.

**Comment by ihrwein** [comment]
@coolreader18 I'm adding a bit more docs around feature flags, they should appear on docs.rs after the release.

One last change I was thinking about is the consolidation of the `future` module. Currently we have a `future`, `tokio`, and `async_std` modules, all exposing very similar APIs. 

I am thinking about
* putting `future::retry` and `future::retry_notify` behind the `tokio` and `async-std` feature flags,
* making `future::Retry` available with the `futures` feature flag, custom `Sleeper` could be implemented for any runtimes,
* removing the `tokio` and `async_std` generated modules.

I think this would be still convenient to use for tokio and async-std users, yet it'd provide a smaller API surface. @coolreader18 what do you think?

**Comment by coolreader18** [comment]
@ihrwein I think that sounds good 👍

**Comment by coolreader18** [comment]
@ihrwein would you be able to publish 0.3 as is? I think the way it is is fine; they may be similar apis, but it's for convenience, you wouldn't want to have to pass `TokioSleeper` every time you want to use `retry()`, nor would you want it to break because both `tokio` and `async-std` are in the dependency graph.

**Comment by ihrwein** [comment]
I've published https://crates.io/crates/backoff/0.3.0-alpha.1 Please let me know how it works then I'll publish final 0.3.0.

**Comment by qwandor** [comment]
Looks good to me, except that the async example in the README doesn't compile due to an incorrect `use`.

**Comment by coolreader18** [comment]
Looks like it's working find for me :+1:

**Comment by ihrwein** [comment]
Async example fixed here: https://github.com/ihrwein/backoff/pull/36

0.3.0 is released: https://crates.io/crates/backoff

Thanks everyone for your contributions!
