### ISSUE TITLE
Support overriding the next_backoff value between retries with an Error.

### ISSUE THREAD

**Issue by poljar** [ihrwein/backoff#35]
Some protocols return a value when a request might be served after they return a `429 Too Many Requests` response. This is effectively a transient error where we know the exact time when we should retry our request.

It would be nice if we could check our response and if it contains such info override the `next_backoff` value with a backoff error, for example:

```rust
Error::TooManyRequests(e, Duration::from_secs(the_suggested_value))
```

**Comment by ihrwein** [comment]
Hello @poljar, thanks for suggesting this idea. This could be part of a 0.4.0 release.
