### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by clux** [ihrwein/backoff#51]
Hey there. I was wondering if there was any possibility of drafting a release on crates.io for this?

There are several quality of life improvements in the [commit log since the release in February](https://github.com/ihrwein/backoff/commits/master), and we would like to expose this functionality as well.

Best, and thanks a lot for this crate :pray:

**Comment by nightkr** [comment]
Looks like this happened about a week ago, thanks! https://github.com/ihrwein/backoff/releases/tag/v0.4.0
